# Generated by Django 5.0.5 on 2024-07-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_createdon_bid_ishighest_listing_createdon_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(condition=models.Q(('isHighest', True)), fields=('l', 'i', 's', 't', 'i', 'n', 'g'), name='only_one_winning_bid'),
        ),
    ]
