# Generated by Django 5.0.5 on 2024-07-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid_only_one_winning_bid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bid',
            name='only_one_winning_bid',
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(condition=models.Q(('isHighest', True)), fields=('listing',), name='only_one_winning_bid'),
        ),
    ]
