# Generated by Django 5.0.5 on 2024-07-02 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_bid_only_one_winning_bid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bid',
            name='only_one_winning_bid',
        ),
    ]
